### ISSUE TITLE
incorrect values in trigonometry functions Asin and Acos

### ISSUE THREAD

**Issue by spin973** [c-ohle/RationalNumerics#10]
I noticed some values returned by arc trigonometry functions are not correct:

Asin(1) return 0 instead of 1.570796 rad (90°)
Acos(0) return 0 instead of 1.570796 rad (90°)

**Comment by c-ohle** [comment]
Hi, Thanks for the bug report. I'll fix that soon.

**Comment by spin973** [comment]
Thank you very much.

**Comment by c-ohle** [comment]
fixed
