### ISSUE TITLE
Updating packages?

### ISSUE THREAD

**Issue by molarmanful** [c-ohle/RationalNumerics#8]
Hi, first of all this project is awesome!

I've been test-driving the code in F# with .NET 7.0 preview using the `BigRational` NuGet package. However, it appears that explicit casting to `BigInt` wasn't added to the project codebase until more recently, so I haven't been able to try out the newer changes. When is the next package expected to be released?

Alternatively, do you happen to know of a way to reference this GitHub repo using Paket? I've tried something like adding the `paket add c-ole/RationalNumerics` but that didn't seem to work.

Thanks in advance for your help!

**Comment by c-ohle** [comment]
Hi, thanks for response and testing. It is for NET 7 all in development. Every week new versions, interface changes especially also vor System.Numerics. Best get latest code and NET7 runtime from the latest dev-brunch: 

https://github.com/dotnet/installer

![image](https://user-images.githubusercontent.com/63112403/187028535-52ceaebc-7b74-4855-9c95-e50a0cdb9633.png)

Now NET7 is in beta and hopefully not more so much general changes. The and when the new floating-point template extension (Float128,Float 256,...is ready a next Nuget package will come. 
And currently also the docu etc. - all not more up to date. Lot of work.

**Comment by molarmanful** [comment]
Great, thanks for the reply! Luckily, manually cloning the repo + building worked just fine. I'll be on the lookout for more updates!

**Comment by c-ohle** [comment]
new check ins every day, optimizations, details, if you find issues I would be happy...
